package oops;


public class Class2 extends Class1 {
	
	public Class2() {
		super();
	}
	
	@Override
	public void test3() {
		super.test3();               // both class will be generated by using "super" in override
		
	}
	public void test4() {
		
		}
		
	}


